quarkus.langchain4j.mcp.coffee-app.transport-type=stdio
quarkus.langchain4j.mcp.coffee-app.command=java,-jar,../langchain4j-playground-mcp-server/target/langchain4j-playground-mcp-server-1.0-SNAPSHOT-runner.jar
quarkus.langchain4j.mcp.coffee-app.log-requests=true
quarkus.langchain4j.mcp.coffee-app.log-responses=true

quarkus.langchain4j.chat-model.provider=ai-gemini

quarkus.langchain4j.ai.gemini.api-key=${GOOGLE_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash

quarkus.langchain4j.openai.chat-model.model-name=gpt-4.1-mini
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.chat-memory.memory-window.max-messages=10