%dev.quarkus.console.enabled=false
quarkus.langchain4j.timeout=300s
quarkus.langchain4j.chat-model.provider=ai-gemini

quarkus.langchain4j.ai.gemini.api-key=${GOOGLE_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash

# Include prompts and completions in spans (disable in production)
quarkus.langchain4j.tracing.include-prompt=true
quarkus.langchain4j.tracing.include-completion=true

quarkus.otel.service.name=langchain4j-observability

#Enable Otel logs
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
