quarkus.langchain4j.timeout=3000s
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.chat-memory.memory-window.max-messages=10
quarkus.langchain4j.ai.gemini.api-key=${GOOGLE_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.0-flash